<?php
$snow_eventos = [
    [
        'titulo'         => 'Neisser: Solo Tour 2026',
        'slug'           => 'neisser-solo-tour-2026',
        'fecha'          => '21 JUL',
        'fecha_completa' => '21 JUL 2026',
        'hora'           => '21:00H',
        'lugar'          => 'Teatro Salesiano',
        'ciudad'         => 'Madrid',
        'pais'           => 'España',
        'pais_bandera'   => '🇪🇸',
        'talento'        => 'Neisser',
        'tipo'           => 'Stand Up',
        'estados'        => ['nuevo', 'destacado'],
        'descripcion'    => 'El monólogo más esperado del año llega a Madrid. Neisser vuelve con material completamente nuevo, más personal y más brutal que nunca.',
        'imagen'         => 'https://picsum.photos/seed/evento1/600/800',
        'galeria'        => [
            'https://picsum.photos/seed/g1a/800/600',
            'https://picsum.photos/seed/g1b/800/600',
            'https://picsum.photos/seed/g1c/800/600',
            'https://picsum.photos/seed/g1d/800/600',
            'https://picsum.photos/seed/g1e/800/600',
            'https://picsum.photos/seed/g1f/800/600',
            'https://picsum.photos/seed/g1g/800/600',
        ],
        'link_compra'    => '#',
    ],
    [
        'titulo'         => 'DJ Camilo: La Noche Perfecta',
        'slug'           => 'dj-camilo-la-noche-perfecta',
        'fecha'          => '05 AGO',
        'fecha_completa' => '05 AGO 2026',
        'hora'           => '23:00H',
        'lugar'          => 'Estadio Obras',
        'ciudad'         => 'Buenos Aires',
        'pais'           => 'Argentina',
        'pais_bandera'   => '🇦🇷',
        'talento'        => 'DJ Camilo',
        'tipo'           => 'Música',
        'estados'        => ['ultimos-tickets'],
        'descripcion'    => 'Una noche de música electrónica y reggaeton que no olvidarás. DJ Camilo trae su set más épico a Buenos Aires.',
        'imagen'         => 'https://picsum.photos/seed/evento2/600/800',
        'galeria'        => [
            'https://picsum.photos/seed/g2a/800/600',
            'https://picsum.photos/seed/g2b/800/600',
            'https://picsum.photos/seed/g2c/800/600',
            'https://picsum.photos/seed/g2d/800/600',
            'https://picsum.photos/seed/g2e/800/600',
            'https://picsum.photos/seed/g2f/800/600',
        ],
        'link_compra'    => '#',
    ],
    [
        'titulo'         => 'SNOW* Festival Primavera',
        'slug'           => 'snow-festival-primavera-2026',
        'fecha'          => '12 SEP',
        'fecha_completa' => '12 SEP 2026',
        'hora'           => '18:00H',
        'lugar'          => 'Foro Sol',
        'ciudad'         => 'Ciudad de México',
        'pais'           => 'México',
        'pais_bandera'   => '🇲🇽',
        'talento'        => 'Varios Artistas',
        'tipo'           => 'Festival',
        'estados'        => ['sold-out'],
        'descripcion'    => 'El festival más grande del año con más de 20 artistas en escena. Tres escenarios, dos días, una experiencia única.',
        'imagen'         => 'https://picsum.photos/seed/evento3/600/800',
        'galeria'        => [
            'https://picsum.photos/seed/g3a/800/600',
            'https://picsum.photos/seed/g3b/800/600',
            'https://picsum.photos/seed/g3c/800/600',
            'https://picsum.photos/seed/g3d/800/600',
            'https://picsum.photos/seed/g3e/800/600',
            'https://picsum.photos/seed/g3f/800/600',
            'https://picsum.photos/seed/g3g/800/600',
            'https://picsum.photos/seed/g3h/800/600',
        ],
        'link_compra'    => '#',
    ],
    [
        'titulo'         => 'Goyo Jiménez: Sin Filtro',
        'slug'           => 'goyo-jimenez-sin-filtro',
        'fecha'          => '27 SEP',
        'fecha_completa' => '27 SEP 2026',
        'hora'           => '20:30H',
        'lugar'          => 'Teatre Grec',
        'ciudad'         => 'Barcelona',
        'pais'           => 'España',
        'pais_bandera'   => '🇪🇸',
        'talento'        => 'Goyo Jiménez',
        'tipo'           => 'Stand Up',
        'estados'        => ['nueva-fecha'],
        'descripcion'    => 'Después del éxito arrollador de su gira, Goyo Jiménez regresa a Barcelona con su espectáculo "Sin Filtro". ¡Nueva fecha confirmada!',
        'imagen'         => 'https://picsum.photos/seed/evento4/600/800',
        'galeria'        => [
            'https://picsum.photos/seed/g4a/800/600',
            'https://picsum.photos/seed/g4b/800/600',
            'https://picsum.photos/seed/g4c/800/600',
            'https://picsum.photos/seed/g4d/800/600',
            'https://picsum.photos/seed/g4e/800/600',
            'https://picsum.photos/seed/g4f/800/600',
        ],
        'link_compra'    => '#',
    ],
    [
        'titulo'         => 'TEDx SNOW*: Ideas que Mueven',
        'slug'           => 'tedx-snow-ideas-que-mueven',
        'fecha'          => '18 OCT',
        'fecha_completa' => '18 OCT 2026',
        'hora'           => '10:00H',
        'lugar'          => 'Centro Cultural Córdoba',
        'ciudad'         => 'Córdoba',
        'pais'           => 'Argentina',
        'pais_bandera'   => '🇦🇷',
        'talento'        => 'Varios Speakers',
        'tipo'           => 'Conferencia',
        'estados'        => ['una-semana', 'destacado'],
        'descripcion'    => 'Una jornada de charlas inspiradoras con los líderes más influyentes de Latinoamérica. Ideas que cambian perspectivas.',
        'imagen'         => 'https://picsum.photos/seed/evento5/600/800',
        'galeria'        => [
            'https://picsum.photos/seed/g5a/800/600',
            'https://picsum.photos/seed/g5b/800/600',
            'https://picsum.photos/seed/g5c/800/600',
            'https://picsum.photos/seed/g5d/800/600',
            'https://picsum.photos/seed/g5e/800/600',
            'https://picsum.photos/seed/g5f/800/600',
            'https://picsum.photos/seed/g5g/800/600',
        ],
        'link_compra'    => '#',
    ],
    [
        'titulo'         => 'La Sonora Dinámica en Vivo',
        'slug'           => 'la-sonora-dinamica-en-vivo',
        'fecha'          => '08 NOV',
        'fecha_completa' => '08 NOV 2026',
        'hora'           => '22:00H',
        'lugar'          => 'Teatro Diana',
        'ciudad'         => 'Guadalajara',
        'pais'           => 'México',
        'pais_bandera'   => '🇲🇽',
        'talento'        => 'La Sonora Dinámica',
        'tipo'           => 'Música',
        'estados'        => [],
        'descripcion'    => 'La orquesta más famosa de México vuelve a Guadalajara para una noche de salsa, cumbia y ritmos latinos que no podrás olvidar.',
        'imagen'         => 'https://picsum.photos/seed/evento6/600/800',
        'galeria'        => [
            'https://picsum.photos/seed/g6a/800/600',
            'https://picsum.photos/seed/g6b/800/600',
            'https://picsum.photos/seed/g6c/800/600',
            'https://picsum.photos/seed/g6d/800/600',
            'https://picsum.photos/seed/g6e/800/600',
            'https://picsum.photos/seed/g6f/800/600',
        ],
        'link_compra'    => '#',
    ],
];

$snow_portfolio = [
    [
        'titulo' => 'Noche de Stand Up',
        'ciudad' => 'Buenos Aires',
        'pais'   => 'AR',
        'año'    => '2025',
        'imagen' => 'https://picsum.photos/seed/port1/600/400',
        'tipo'   => 'Stand Up',
    ],
    [
        'titulo' => 'Festival SNOW* Primavera',
        'ciudad' => 'Madrid',
        'pais'   => 'ES',
        'año'    => '2024',
        'imagen' => 'https://picsum.photos/seed/port2/600/400',
        'tipo'   => 'Festival',
    ],
    [
        'titulo' => 'Konfu: Live Session',
        'ciudad' => 'Ciudad de México',
        'pais'   => 'MX',
        'año'    => '2024',
        'imagen' => 'https://picsum.photos/seed/port3/600/400',
        'tipo'   => 'Música',
    ],
    [
        'titulo' => 'Conferencia Liderazgo 2024',
        'ciudad' => 'Barcelona',
        'pais'   => 'ES',
        'año'    => '2024',
        'imagen' => 'https://picsum.photos/seed/port4/600/400',
        'tipo'   => 'Conferencia',
    ],
    [
        'titulo' => 'Reggaeton Night Vol. 3',
        'ciudad' => 'Córdoba',
        'pais'   => 'AR',
        'año'    => '2025',
        'imagen' => 'https://picsum.photos/seed/port5/600/400',
        'tipo'   => 'Música',
    ],
    [
        'titulo' => 'Comedy Night Especial',
        'ciudad' => 'Montevideo',
        'pais'   => 'UY',
        'año'    => '2024',
        'imagen' => 'https://picsum.photos/seed/port6/600/400',
        'tipo'   => 'Stand Up',
    ],
];

$snow_badge_map = [
    'nuevo'           => ['label' => 'NUEVO',                 'class' => 'badge--nuevo'],
    'destacado'       => ['label' => 'DESTACADO',             'class' => 'badge--destacado'],
    'ultimos-tickets' => ['label' => 'ÚLTIMOS TICKETS',       'class' => 'badge--ultimos'],
    'sold-out'        => ['label' => 'SOLD OUT',              'class' => 'badge--sold-out'],
    'una-semana'      => ['label' => 'A TAN SOLO UNA SEMANA', 'class' => 'badge--una-semana'],
    'nueva-fecha'     => ['label' => 'NUEVA FECHA AGREGADA',  'class' => 'badge--nueva-fecha'],
];

function snow_render_badges(array $estados, array $badge_map, int $max = 2): string {
    if (empty($estados)) return '';
    $html  = '<div class="snow-badges">';
    $count = count($estados);
    $show  = array_slice($estados, 0, $max);
    foreach ($show as $estado) {
        if (!isset($badge_map[$estado])) continue;
        $b     = $badge_map[$estado];
        $html .= '<span class="snow-badge ' . esc_attr($b['class']) . '">' . esc_html($b['label']) . '</span>';
    }
    if ($count > $max) {
        $html .= '<span class="snow-badge badge--more">+' . ($count - $max) . '</span>';
    }
    $html .= '</div>';
    return $html;
}
